version: '2.0'

networks:
  guacnetwork_compose:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
      - ./drive:/drive:z
      - ./record:/record:z
  # postgres
  postgres:
    container_name: postgres_guacamole
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: '(generate)'
      POSTGRES_USER: guacamole_user
    image: postgres:13.4
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:z

  # guacamole
  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: '(generate)'
      POSTGRES_USER: guacamole_user
      LDAP_HOSTNAME: falloutstrike.jetfalcon.nz
      LDAP_PORT: 389
      LDAP_ENCRYPTION_METHOD: none
      LDAP_USER_BASE_DN: OU=Users,OU=STORMBREAKER,DC=jetfalcon,DC=nz
      LDAP_SEARCH_BIND_DN: svc_guac@jetfalcon.nz
      LDAP_SEARCH_BIND_PASSWORD: (removed)
      LDAP_USERNAME_ATTRIBUTE: sAMAccountName
      GUACAMOLE_HOME: /config
    image: guacamole/guacamole
    links:
      - guacd
    volumes:
      - ./config:/config:z
    networks:
      guacnetwork_compose:
    ports:
      - 9080:8080/tcp
    restart: always

  nginx:
    container_name: guacamole_nginx
    restart: always
    image: nginx
    volumes:
      - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:z
      - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:z
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/guacamole.conf:/etc/nginx/conf.d/default.conf:z
    ports:
      - 443:443
    links:
      - guacamole
    networks:
      guacnetwork_compose:
